name: CI/CD pipeline

on:
  push:
    branches: ["master"]

permissions:
  contents: write
  id-token: write

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #git clone - download repo-code onto runner machine

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Increment patch version
        run: |
          CURRENT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          PATCH=$((PATCH + 1))

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"

          echo "New version: $NEW_VERSION"
          
          mvn -B versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    
      - name: Build project
        run: mvn -B clean test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sasha-maven:${{ env.NEW_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sasha-maven:latest

      - name: Commit and push version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Patch version increased to $NEW_VERSION"
          git push

      - name: Configure AWS credentials      
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::495930421236:role/GithubActionsDeploy
          aws-region: eu-north-1

      - name: Deploy container to EC2 via SSM
        run: |
          aws ssm send-command \
            --instance-ids "i-053d4355a206edced" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy java app container" \
            --parameters \
              commands="docker pull sashak9/sasha-maven:latest" \
              commands="docker stop java-deploy || true" \
              commands="docker rm java-deploy || true" \
              commands="docker image prune -f" \
              commands="docker run --name java-deploy sashak9/sasha-maven:latest"

