name: CI/CD pipeline

on:
  push:
    branches: ["master"]

permissions:
  contents: write

jobs:
  increment-patch-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 #git clone - download repo-code onto runner machine

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Increment patch version
        run: |
          CURRENT=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $CURRENT"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          PATCH=$((PATCH + 1))

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"

          echo "New version: $NEW_VERSION"
          
          mvn -B versions:set -DnewVersion=${NEW_VERSION} -DgenerateBackupPoms=false
          
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
    
      - name: Build project
        run: mvn -B clean test

      - name: Commit and push version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "Patch version increased to $NEW_VERSION"
          git push
